import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

export const COLORS = {
  primary: [17, 17, 17],
  accent: [230, 57, 70],
  gray: [128, 128, 128],
  lightGray: [245, 245, 245],
  border: [220, 220, 220],
};

export const MM_TO_PT = 2.8346;
export const PAGE_HEIGHT = 297; // A4 height in mm
export const PAGE_WIDTH = 210; // A4 width in mm
export const MARGIN = 15;
export const CONTENT_WIDTH = PAGE_WIDTH - (MARGIN * 2);

export const setDocumentStyles = (doc, isDark = false) => {
  if (isDark) {
    doc.setFillColor(10, 10, 10);
    doc.rect(0, 0, 210, 297, 'F');
    doc.setTextColor(255, 255, 255);
  }
};

export const addHeader = (doc, title, subtitle) => {
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Skip header if not on first page or add to all pages
  doc.setFillColor(245, 245, 245);
  doc.rect(0, 0, pageWidth, 35, 'F');
  
  doc.setFillColor(230, 57, 70);
  doc.rect(0, 0, 4, 35, 'F');
  
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(17, 17, 17);
  doc.text(title, MARGIN, 22);
  
  if (subtitle) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(128, 128, 128);
    doc.text(subtitle, MARGIN, 30);
  }
};

export const addSection = (doc, title, y, addNewPageIfNeeded = true) => {
  const pageHeight = doc.internal.pageSize.getHeight();
  const bottomMargin = pageHeight - 20;
  
  if (y > bottomMargin - 20 && addNewPageIfNeeded) {
    doc.addPage();
    return MARGIN + 15;
  }
  
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(230, 57, 70);
  doc.text(title.toUpperCase(), MARGIN, y);
  
  doc.setDrawColor(220, 220, 220);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, y + 3, CONTENT_WIDTH + MARGIN, y + 3);
  
  return y + 10;
};

export const addParagraph = (doc, text, y, fontSize = 10, maxWidth = CONTENT_WIDTH, addNewPageIfNeeded = true) => {
  const pageHeight = doc.internal.pageSize.getHeight();
  const bottomMargin = pageHeight - 20;
  
  if (!text) {
    return y + 10;
  }
  
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(fontSize);
  doc.setTextColor(17, 17, 17);
  
  const str = String(text);
  const lines = doc.splitTextToSize(str, maxWidth);
  const lineHeight = fontSize * 0.45 + 2;
  const totalHeight = lines.length * lineHeight;
  
  if (y + totalHeight > bottomMargin && addNewPageIfNeeded) {
    doc.addPage();
    y = MARGIN + 10;
  }
  
  doc.text(str, MARGIN, y);
  
  return y + totalHeight + 3;
};

export const addBulletList = (doc, items, y, maxWidth = CONTENT_WIDTH, addNewPageIfNeeded = true) => {
  const pageHeight = doc.internal.pageSize.getHeight();
  const bottomMargin = pageHeight - 20;
  
  if (!items || !Array.isArray(items)) {
    return y;
  }
  
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(17, 17, 17);
  
  items.forEach((item) => {
    if (!item) return;
    
    const str = String(item);
    
    if (y > bottomMargin - 10 && addNewPageIfNeeded) {
      doc.addPage();
      y = MARGIN + 10;
    }
    
    doc.text('•', MARGIN + 3, y);
    doc.text(str, MARGIN + 10, y);
    
    y += 8;
  });
  
  return y + 5;
};

export const addTable = (doc, headers, data, y, addNewPageIfNeeded = true) => {
  autoTable(doc, {
    head: [headers],
    body: data,
    startY: y,
    margin: { left: MARGIN, right: MARGIN },
    styles: {
      fontSize: 9,
      cellPadding: 4,
    },
    headStyles: {
      fillColor: [17, 17, 17],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
    },
    alternateRowStyles: {
      fillColor: [245, 245, 245],
    },
    pageBreak: addNewPageIfNeeded ? 'auto' : 'avoid',
  });
  
  return doc.lastAutoTable.finalY + 10;
};

export const addFooter = (doc, text, pageCount) => {
  const pageHeight = doc.internal.pageSize.getHeight();
  const pageWidth = doc.internal.pageSize.getWidth();
  const totalPages = doc.internal.getNumberOfPages();
  
  doc.setFontSize(8);
  doc.setTextColor(180, 180, 180);
  const footerText = text || 'Generated by ThreeFoldHub Tools';
  doc.text(footerText, pageWidth / 2, pageHeight - 10, { align: 'center' });
  doc.text('Page ' + (pageCount || totalPages), pageWidth - MARGIN, pageHeight - 10);
};

export const addSignatureBlock = (doc, y, leftLabel, rightLabel, addNewPageIfNeeded = true) => {
  const pageHeight = doc.internal.pageSize.getHeight();
  const bottomMargin = pageHeight - 20;
  const lineHeight = 25;
  
  if (y + lineHeight + 20 > bottomMargin && addNewPageIfNeeded) {
    doc.addPage();
    y = MARGIN + 10;
  }
  
  const labelY = y;
  
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(17, 17, 17);
  doc.text(leftLabel, MARGIN, labelY);
  doc.text(rightLabel, 130, labelY);
  
  doc.setDrawColor(100, 100, 100);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, labelY + lineHeight, 90, labelY + lineHeight);
  doc.line(130, labelY + lineHeight, 195, labelY + lineHeight);
  
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(128, 128, 128);
  doc.text('Signature', 45, labelY + lineHeight + 6);
  doc.text('Signature', 160, labelY + lineHeight + 6);
  
  doc.line(MARGIN, labelY + lineHeight + 12, 90, labelY + lineHeight + 12);
  doc.line(130, labelY + lineHeight + 12, 195, labelY + lineHeight + 12);
  
  doc.text('Date', 45, labelY + lineHeight + 18);
  doc.text('Date', 160, labelY + lineHeight + 18);
  
  return y + lineHeight + 30;
};

export const checkAndAddPage = (doc, y, needed = 30, headerTitle = '') => {
  const pageHeight = doc.internal.pageSize.getHeight();
  const bottomMargin = pageHeight - 25;
  
  if (y + needed > bottomMargin) {
    doc.addPage();
    const pageWidth = doc.internal.pageSize.getWidth();
    doc.setFillColor(245, 245, 245);
    doc.rect(0, 0, pageWidth, 20, 'F');
    if (headerTitle) {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.setTextColor(128, 128, 128);
      doc.text(headerTitle, MARGIN, 13);
    }
    return MARGIN + 10;
  }
  return y;
};

export const generateDocument = (title, contentFn, filename) => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });
  
  contentFn(doc);
  
  doc.save(filename);
};

export default {
  COLORS,
  MM_TO_PT,
  PAGE_HEIGHT,
  PAGE_WIDTH,
  MARGIN,
  CONTENT_WIDTH,
  setDocumentStyles,
  addHeader,
  addSection,
  addParagraph,
  addBulletList,
  addTable,
  addFooter,
  addSignatureBlock,
  checkAndAddPage,
  generateDocument,
};