import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

export const COLORS = {
  primary: [17, 17, 17],
  accent: [230, 57, 70],
  gray: [128, 128, 128],
  lightGray: [245, 245, 245],
  border: [220, 220, 220],
};

export const FONTS = {
  heading: 'helvetica',
  body: 'helvetica',
};

export const setDocumentStyles = (doc, isDark = false) => {
  if (isDark) {
    doc.setFillColor(10, 10, 10);
    doc.rect(0, 0, 210, 297, 'F');
    doc.setTextColor(255, 255, 255);
  }
};

export const addHeader = (doc, title, subtitle = '', accentColor = COLORS.accent) => {
  const pageWidth = doc.internal.pageSize.getWidth();
  
  doc.setFillColor(...COLORS.lightGray);
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setFillColor(...accentColor);
  doc.rect(0, 0, 4, 40, 'F');
  
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(...COLORS.primary);
  doc.text(title, 15, 25);
  
  if (subtitle) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(...COLORS.gray);
    doc.text(subtitle, 15, 33);
  }
};

export const addSection = (doc, title, y) => {
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(...COLORS.accent);
  doc.text(title.toUpperCase(), 15, y);
  
  doc.setDrawColor(...COLORS.border);
  doc.setLineWidth(0.5);
  doc.line(15, y + 2, 195, y + 2);
  
  return y + 10;
};

export const addParagraph = (doc, text, y, fontSize = 10, maxWidth = 175) => {
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(fontSize);
  doc.setTextColor(...COLORS.primary);
  
  const lines = doc.splitTextToSize(text, maxWidth);
  doc.text(lines, 15, y);
  
  return y + (lines.length * fontSize * 0.4) + 5;
};

export const addBulletList = (doc, items, y, maxWidth = 175) => {
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(...COLORS.primary);
  
  items.forEach((item, idx) => {
    const bullet = '•';
    doc.text(bullet, 18, y + (idx * 6));
    
    const lines = doc.splitTextToSize(item, maxWidth - 10);
    doc.text(lines, 25, y + (idx * 6));
  });
  
  return y + (items.length * 6) + 5;
};

export const addTable = (doc, headers, data, y) => {
  autoTable(doc, {
    head: [headers],
    body: data,
    startY: y,
    margin: { left: 15, right: 15 },
    styles: {
      fontSize: 9,
      cellPadding: 4,
    },
    headStyles: {
      fillColor: COLORS.primary,
      textColor: [255, 255, 255],
      fontStyle: 'bold',
    },
    alternateRowStyles: {
      fillColor: COLORS.lightGray,
    },
  });
  
  return doc.lastAutoTable.finalY + 10;
};

export const addFooter = (doc, text = 'Generated by ThreeFoldHub Tools') => {
  const pageHeight = doc.internal.pageSize.getHeight();
  
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.gray);
  doc.text(text, 105, pageHeight - 10, { align: 'center' });
  doc.text(`Page 1`, 185, pageHeight - 10);
};

export const addSignatureBlock = (doc, y, leftLabel = 'Client', rightLabel = 'ThreeFoldHub') => {
  const lineHeight = 25;
  const labelY = y;
  
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(...COLORS.primary);
  doc.text(leftLabel, 15, labelY);
  doc.text(rightLabel, 130, labelY);
  
  doc.setDrawColor(...COLORS.primary);
  doc.setLineWidth(0.5);
  doc.line(15, labelY + lineHeight, 90, labelY + lineHeight);
  doc.line(130, labelY + lineHeight, 195, labelY + lineHeight);
  
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.gray);
  doc.text('Signature', 45, labelY + lineHeight + 8);
  doc.text('Signature', 160, labelY + lineHeight + 8);
  
  doc.line(15, labelY + lineHeight + 15, 90, labelY + lineHeight + 15);
  doc.line(130, labelY + lineHeight + 15, 195, labelY + lineHeight + 15);
  
  doc.text('Date', 45, labelY + lineHeight + 23);
  doc.text('Date', 160, labelY + lineHeight + 23);
  
  return y + lineHeight + 30;
};

export const generateDocument = (title, contentFn, filename) => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });
  
  contentFn(doc);
  
  doc.save(filename);
};

export default {
  COLORS,
  setDocumentStyles,
  addHeader,
  addSection,
  addParagraph,
  addBulletList,
  addTable,
  addFooter,
  addSignatureBlock,
  generateDocument,
};